---
deployment:
  tasks:
    # - export DEPLOYPATH=/home/connexx1/public_html/
    - export DEPLOYPATH=/home/connexx1/public_html/cnxretail.connexxiontelecom.com/
    - /bin/cp -R * $DEPLOYPATH
